config/routes.rb
TttWeb::Application.routes.draw do
  resources :saved_games do
    member do
      post 'play'
    end
  end

  resources :api_games do
    member do
      post 'play'
    end
  end

  resources :mail_games do
    collection do
      post 'play'
    end
  end

  root 'home#index'
end

app/models/saved_game.rb
class SavedGame < ActiveRecord::Base
  def lost?
    status == 'lost'
  end

  def play_turn(x, y)
    game.place(x, y)
    
    unless game.finish?
      player = Player.new(game, 1)
      player.play
    end

    self.data = game.save
    
    if game.winner == -1
      self.status = 'won'
    elsif game.winner == 1
      self.status = 'lost'
    end

    save

  end

  def game
    @game ||= Game::load(data)
  end

  def grid_s
    grid_str = "  0 1 2\n"
    (0..2).each do |y|
      grid_str << y.to_s + " " 
      (0..2).each do |x|
        grid_str << game.show_at(y,x) + " "
      end
      grid_str << "\n"
    end
    grid_str
  end
end

app/controllers/api_games_controller.rb
class ApiGamesController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @saved_games = SavedGame.all
  end

  def show
    @saved_game = SavedGame.find(params[:id])
  end

  def play
    @saved_game = SavedGame.find(params[:id])

    x = params[:x].to_i
    y = params[:y].to_i

    @saved_game.play_turn(x, y)

    render action: 'show', status: :created, location: @saved_game
  end

  # POST /saved_games
  # POST /saved_games.json
  def create
    @saved_game = SavedGame.new
    @saved_game.status = 'ongoing'
    game = Game.new(1)
    player = Player.new(game, 1)
    player.play
    
    @saved_game.data = game.save
    @saved_game.save

    render action: 'show', status: :created, location: @saved_game
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def saved_game_params
      params.require(:saved_game).permit(:data)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mail_games_controller.rb
class MailGamesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  def index
    @saved_games = SavedGame.all
  end

  def play
    message = JSON.parse(request.body.read)
    title = message["Subject"]
    body = message["TextBody"]

    id = /TTTGame-(\d+)\s/.match(title)[1].to_i

    first_line = body.lines.first
    x = first_line[0].to_i
    y = first_line[2].to_i

    @saved_game = SavedGame.find(id)
    @saved_game.play_turn(x, y)

    status = @saved_game.status
    body_contents = "TTTGame-#{id} is #{status} - your move!\n Grid: \n #{@saved_game.grid_s}\n Play by replying to this mail."
    
    message = Mail.new do
      from            'you.from@mail.com'
      reply_to        "postmarkinbound@inbound.postmarkapp.com"
      to              'you.to@mail.com'
      subject         "TTTGame-#{id} is #{status}!"
      body            body_contents

      delivery_method Mail::Postmark, :api_key => ENV['POSTMARK_API_KEY']
    end

    message.deliver

    render status: 200
  end

  def new
    @saved_game = SavedGame.new
    @saved_game.status = 'ongoing'
    
    game = Game.new(1)
    player = Player.new(game, 1)
    player.play

    @saved_game.data = game.save
    @saved_game.save

    id = @saved_game.id
    body_contents = "TTTGame-#{id} has just started - your move!\n Grid: \n #{@saved_game.grid_s}\n Play by replying to this mail."

    message = Mail.new do
      from            'you.from@mail.com'
      reply_to        "postmarkinbound@inbound.postmarkapp.com"
      to              'you.to@mail.com'
      subject         "TTTGame-#{id} has started!"
      body            body_contents

      delivery_method Mail::Postmark, :api_key => ENV['POSTMARK_API_KEY']
    end

    message.deliver

    redirect_to action: 'index', notice: 'Game started !'
  end

end

app/controllers/saved_games_controller.rb
class SavedGamesController < ApplicationController

  def index
    @saved_games = SavedGame.all
  end

  def show
    @saved_game = SavedGame.find(params[:id])
  end

  def play
    @saved_game = SavedGame.find(params[:id])

    x = params[:x].to_i
    y = params[:y].to_i

    @saved_game.play_turn(x,y)
    
    redirect_to action: 'show'
  end

  def new
    @saved_game = SavedGame.new
    @saved_game.status = 'ongoing'
    game = Game.new(1)
    player = Player.new(game, 1)
    player.play

    @saved_game.data = game.save
    @saved_game.save

    redirect_to @saved_game, notice: 'Saved game was successfully created.'
  end

  def destroy
    @saved_game = SavedGame.find(params[:id])
    @saved_game.destroy
    redirect_to saved_games_url
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def saved_game_params
      params.require(:saved_game).permit(:data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/saved_games_helper.rb
module SavedGamesHelper
end

app/views/home/index.html.erb
<h1>Welcome to TTT</h1>
<h2><%= link_to "Play on Web", saved_games_path %></h2>
<h2><%= link_to "Play by email", mail_games_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TttWeb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mail_games/index.html.erb
<h1>Listing mail games</h1>

<%= link_to 'New game', new_mail_game_path %>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>status</th>
      <th>grid</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @saved_games.each do |saved_game| %>
      <tr>
        <td><%= saved_game.id %></td>
        <td><%= saved_game.status %></td>
        <td><pre><%= saved_game.grid_s %></pre></td>
        <td><%= link_to 'Show', saved_game %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/saved_games/_game.html.erb
<table class="game">
  <% (0..2).each do |x| %>
  <tr>
    <% (0..2).each do |y| %>
      <td>
        <% if @saved_game.game.at(x,y) == 0 && !@saved_game.game.finish? %>
          <%= link_to ' ', play_saved_game_path(x: x, y: y), method: :post, id: @saved_game.id %>
        <% else %>
        <%= @saved_game.game.show_at(x,y) %>
        <% end %>
      </td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/saved_games/index.html.erb
<h1>Listing saved_games</h1>
<%= link_to 'New game', new_saved_game_path %>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>status</th>
      <th>grid</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @saved_games.each do |saved_game| %>
      <tr>
        <td><%= saved_game.id %></td>
        <td><%= saved_game.status %></td>
        <td><pre><%= saved_game.grid_s %></pre></td>
        <td><%= link_to 'Show', saved_game %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/saved_games/new.html.erb
<h1>New saved_game</h1>

<%= render 'form' %>

<%= link_to 'Back', saved_games_path %>

app/views/saved_games/show.html.erb
<p id="notice"><%= notice %></p>

<% if @saved_game.game.finish? %>
  <% if @saved_game.lost? %>
    <h1> You lost game <%= @saved_game.id %>!</h1>
  <% else %>
  <h1> You won game <%= @saved_game.id %>!</h1>
  <% end %>
<% else %>
<h1> Game <%= @saved_game.id %></h1>
<% end %>

<%= render 'game' %>

<%= link_to 'Back', saved_games_path %> | <%= link_to 'New game', new_saved_game_path %>